const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');
menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open);});
document.querySelectorAll('.nav a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(item=>observer.observe(item));
const dialog=document.querySelector('.lightbox'),lightboxArt=dialog.querySelector('.lightbox-art'),lightboxTitle=dialog.querySelector('p');
document.querySelectorAll('.gallery-card').forEach(card=>card.addEventListener('click',()=>{lightboxArt.style.backgroundImage='';lightboxArt.classList.remove('has-image');lightboxTitle.textContent=card.dataset.title;dialog.showModal();}));
document.querySelectorAll('[data-image]').forEach(item=>item.addEventListener('click',()=>{lightboxArt.style.backgroundImage=`url("${item.dataset.image}")`;lightboxArt.classList.add('has-image');lightboxTitle.textContent=item.dataset.title;dialog.showModal();}));
document.querySelector('.close-lightbox').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});
